version: '3.1'

services:
  php:
    build:
      context: .
    volumes:
      - D:\OpenServer\domains\MVC:/var/www/html
    ports:
      - 8081:80
    links:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1234

