<?php
/** @var array $data */

$errorsDescription = explode('<br>', file_get_contents(PROJECT_ROOT_DIR .
    DIRECTORY_SEPARATOR . 'src' . DIRECTORY_SEPARATOR . "Errors.html", 1));


?>

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../../html/css/style.css">

    <title>Document</title>
</head>
<body>

<h1 style="color: white">Отправить сообщение</h1>
<hr>
<form action="/html/blog/send" method="post" enctype="multipart/form-data">
    <textarea name="text"></textarea><br>
    <input type="file" name="image" style="color: white;"><br>
    <input type="submit">
</form>


<h1 style="color: white">Сообщения</h1>
<hr>
<?php

foreach ($data['messages'] as $message):
    echo "<div class='user_info_wrap'>";

    ?>

    <p class="user_info">Имя: </p> <p class="user_info_data"><?= $message['name'] ?></p><br>
    <p class="user_info">Дата: </p> <p class="user_info_data"><?= $message['date'] ?></p><br>
    <?= "<p class='user_info_data'>", $message['text'], "</p>" ?><br>

    <?php

    $path = ".." . DIRECTORY_SEPARATOR . ".." .
        DIRECTORY_SEPARATOR . ".." .
        DIRECTORY_SEPARATOR . "html" .
        DIRECTORY_SEPARATOR . "img" .
        DIRECTORY_SEPARATOR;

    if (!empty($message['image_src'])) {
        echo "<img src='{$path}{$message['image_src']}' style='width:100px;height:100px;'>";
    }

    if (in_array($_SESSION['id'], ADMINS)) {
        echo "<form action='/html/blog/delete' method='post'>
   <input type='hidden' value='{$message['id']}' name='id'>
   <input type='submit' value='удалить' class='delete_message_btn'>

    </form>";
    }
    ?>
    <?= "</div>" ?>

<?php endforeach; ?>


</body>
</html>
