<?php
$fieldsToHighlihgt = array_combine(array_keys(FIELDS_ERRORS_CORRESPONDS),
    array_fill(0, count(FIELDS_ERRORS_CORRESPONDS), false));

foreach (FIELDS_ERRORS_CORRESPONDS as $key => $errorCodes) {
    foreach (json_decode($_COOKIE['errors']) ?? [] as $errCode) {
        if (in_array($errCode, $errorCodes)) {
            $fieldsToHighlihgt[$key] = true;
        }
    }
}

?>


<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../../../html/css/style.css">
    <title>Document</title>
</head>
<body>

<h1 style="color: white;">Авторизация</h1>
<hr>
<form action="/html/user/authorization" method="post">
    <input type="email" style="border: 2px solid <?= ($fieldsToHighlihgt['email']) ? 'red' : 'black' ?>"
           placeholder="введите email" name="email">
    <input type="text" style="border: 2px solid <?= ($fieldsToHighlihgt['name']) ? 'red' : 'black' ?>"
           placeholder="введите имя" name="name">
    <input type="password" style="border: 2px solid <?= ($fieldsToHighlihgt['password']) ? 'red' : 'black' ?>"
           placeholder="введите пароль" name="password">
    <input type="submit">
</form>

<a href="/html/user/register" class="redirect_link">Регистрация</a>

</body>
</html>