<?php

namespace Core;

\define('OK', 0);
\define('NAME_INCORRECT_LENGTH_MIN', 1);
\define('PASSWORD_INCORRECT_LENGTH_MIN', 2);
\define('EMAIL_ALREADY_EXIST_REGISTRATION', 3);
\define('NAME_ALREADY_EXIST_REGISTRATION', 4);
\define('INCORRECT_EMAIL', 5);
\define('USER_NOT_EXIST', 6);
\define('PASSWORDS_IN_FORM_NOT_MATCHES', 7);
\define('EMPTY_EMAIL_FORM', 8);
\define('EMPTY_NAME_FORM', 9);
\define('EMPTY_PASSWORD_FORM', 10);
\define('EMPTY_FIELDS', 11);
\define('PASSWORDS_NOT_MATCHES', 12);
\define('EMAIL_NOT_EXIST', 13);
\define('USER_NOT_AUTHORIZED', 14);
\define('EMPTY_MESSAGE_TEXT', 15);
\define('INCORRECT_IMAGE_TYPE', 16);
\define('PASSWORD_INCORRECT_LENGTH_MAX', 17);
\define('NAME_INCORRECT_LENGTH_MAX', 18);
\define('MESSAGE_TEXT_INCORRECT_LENGTH_MAX', 19);
\define('EMAIL_INCORRECT_LENGTH_MIN', 20);
\define('EMAIL_INCORRECT_LENGTH_MAX', 20);
